version: '3'
volumes:
  graylog_db-volume:
    driver: local
  graylog-volume:
    driver: local
  graylog_db_config-volume:
    driver: local
services:
  mongo:
    image: mongo:3
    volumes:
    - graylog_db_config-volume:/data/configdb
    - graylog_db-volume:/data/db
    deploy:
      replicas: 1
      placement:
         constraints:
            - node.hostname == laas-lab-local-1
  graylog:
    image: graylog/graylog:2.3
    environment:
      GRAYLOG_ELASTICSEARCH_HOSTS: http://elasticsearch:9200
      GRAYLOG_PASSWORD_SECRET: somepasswordpepper
      GRAYLOG_ROOT_PASSWORD_SHA2: 19dd7e0054958080ad0249828f56b6f4d2a274fb5bfb79adccbaeceb0db66265
      GRAYLOG_WEB_ENDPOINT_URI: http://192.168.122.60:9001/api
    volumes:
    - graylog-volume:/usr/share/graylog/data
    ports:
    - 514:514/tcp
    - 515:515/tcp
    - 9001:9000/tcp
    deploy:
      replicas: 1
      placement:
         constraints:
            - node.hostname == laas-lab-local-1
networks:
  default:
    external:
       name: swarm-overlay-1
