{
 "title": "Standalone Server: Graylog details",
 "description": "System metrics from Graylog",
 "tags": [
  "System",
  "Syslog",
  "Auth",
  "Elasticsearch"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Node",
    "query": "{\"find\": \"terms\", \"field\": \"source\"}"
   },
   {
    "name": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "Filter" }
  ]
 },
 "panels": [
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Message count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "source: $Node",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Severity - Last 1h",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "source: $Node AND level: \"1\" OR level: \"2\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Failed ssh root logins",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "source: $Node AND application_name: \"sshd\" AND message: \"Failed password for root from\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Failed ssh user logins",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "source: $Node AND application_name: \"sshd\" AND message: \"Failed password for\" AND NOT message: \"Failed password for root\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Failed sudo auth",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "source: $Node AND application_name: \"sudo\" AND message: \"authentication failure\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "content": "<p align=\"center\"><h3 style=\"text-align: center;\" markdown=\"1\">\n<a href=http://skullkid.dlinkddns.com:3300 target=\"_blank\"><img src=https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/Graylog-logo-blk.jpg/220px-Graylog-logo-blk.jpg height=100></a></h3></p>"
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Syslog Facilities",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "facility",
       "id": "5",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "timestamp",
       "id": "4",
       "settings": { "interval": "$Interval", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "facility",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "source: $Node AND NOT facility: winlogbeat",
     "timeField": "timestamp"
    },
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "winlogbeat_winlog_channel",
       "id": "5",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "timestamp",
       "id": "4",
       "settings": { "interval": "$Interval", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "facility",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "source: $Node AND facility: winlogbeat",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Syslog Facilities Histogram",
   "type": "graph",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "facility",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "20" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "$Interval", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "source: $Node AND NOT facility: winlogbeat",
     "timeField": "timestamp"
    },
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "winlogbeat_winlog_channel",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "20" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "$Interval", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "source: $Node AND facility: winlogbeat",
     "timeField": "timestamp"
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Syslog Applications - Top 10",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 14 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "application_name",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "timestamp",
       "id": "3",
       "settings": {
        "interval": "auto",
        "min_doc_count": 1,
        "trimEdges": null
       },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "facility",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "source: $Node AND NOT facility: winlogbeat",
     "timeField": "timestamp"
    },
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "winlogbeat_winlog_provider_name",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "timestamp",
       "id": "3",
       "settings": {
        "interval": "auto",
        "min_doc_count": 1,
        "trimEdges": null
       },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "facility",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "source: $Node AND facility: winlogbeat",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Syslog Applications Histogram - Top 10",
   "type": "graph",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "application_name",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "$Interval", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "source: $Node AND NOT facility: winlogbeat",
     "timeField": "timestamp"
    },
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "winlogbeat_winlog_provider_name",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "$Interval", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "source: $Node AND facility: winlogbeat",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Root login and sudo success / fail",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 }
  },
  {
   "title": "Failed IPs root login - Top 10",
   "type": "table",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 22 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "message_ip",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "source: $Node AND application_name: \"sshd\" AND message: \"Failed password for root from\"",
     "timeField": "timestamp"
    },
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "message_ip",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "source: $Node AND message: \"LAN access from remote\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Failed login root - locations",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 9, "w": 10, "x": 6, "y": 22 },
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "message_ip_country_code",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "source: $Node AND application_name: \"sshd\" AND message: \"Failed password for root from\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Userid sudo command failed",
   "type": "table",
   "gridPos": { "h": 9, "w": 4, "x": 16, "y": 22 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "message_userid",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "source: $Node AND application_name: \"sudo\" AND (message: \"authentication failure\" OR message: \"user NOT in sudoers\")",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Userid sudo session success",
   "type": "table",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 22 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "message_userid",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "source: $Node AND application_name: \"su\" AND message: \"session opened for\"",
     "timeField": "timestamp"
    }
   ]
  },
  { "title": "Additional user login details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "User login success by IP - Top 10",
   "type": "table",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 32 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "message_userid",
       "id": "5",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "message_ip",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "source: $Node AND application_name: \"sshd\" AND message: \"Accepted password for\"",
     "timeField": "timestamp"
    },
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "winlogbeat_event_data_TargetUserName",
       "id": "5",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "winlogbeat_event_data_IpAddress",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "source: $Node AND winlogbeat_log_name: \"Security\" AND message: \"O logon de uma conta foi efetuado com sucesso\" AND winlogbeat_event_data_LogonProcessName: \"User32\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Failed login / External Access (not root) - locations",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 9, "w": 10, "x": 6, "y": 32 },
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "message_ip_country_code",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "source: $Node AND application_name: \"sshd\" AND message: \"Failed password for\" AND NOT \"root\"",
     "timeField": "timestamp"
    },
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "message_ip_country_code",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "source: $Node AND message: \"LAN access from remote\" AND NOT \"root\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Failed userID login - Top 10",
   "type": "table",
   "gridPos": { "h": 9, "w": 4, "x": 16, "y": 32 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "message_userid",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "source: $Node AND application_name: \"sshd\" AND message: \"Failed password\" AND NOT \"invalid user\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Invalid userID login - Top 10",
   "type": "table",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 32 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "message_userid",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "source: $Node AND application_name: \"sshd\" AND message: \"Failed password for invalid user\" AND NOT \"root\"",
     "timeField": "timestamp"
    }
   ]
  }
 ]
}